import type { Product } from "@/lib/types";

export const diastar: Product = {
  slug: "diastar",
  category: "po-film",
  tier: "premium",
  brand: "saemi",
  origin: "Made in Japan · MKV Advance",
  name: { ko: "다이아스타", en: "Diastar" },
  tagline: {
    ko: "타협 없는 탁월함. 한 장이 한 해를 받칩니다.",
  },
  headline: {
    ko: "타협 없는 탁월함\n일본 코팅 PO 필름 No.1",
  },
  intro: {
    ko: "다섯 해, 한 장 — 농가의 한 시즌이 그 위에서 흐릅니다. 빛이 통과하는 방식, 야간 온도가 머무는 방식, 빗방울이 흐르는 방식. 일본 MKV Advance가 오래 다듬어 온 코팅 PO 기술이, 새미를 통해 한국 농업으로 들어옵니다.",
  },
  filmType: "투명",
  thickness: [0.15],
  bigSpecs: [
    { label: "두께", value: "0.15", unit: "mm" },
    { label: "경제수명", value: "5", unit: "년" },
    { label: "원산지", value: "Japan" },
  ],
  highlights: [
    {
      title: "탁월한 내구성과 무적성",
      body: "내구성과 무적성이 탁월한 고품질 장기성 PO필름으로, 필요한 모든 성능을 효과적으로 장기간에 걸쳐 발휘합니다.",
      image: "products/po-film/premium/diastar/hero/exterior-02.webp",
    },
    {
      title: "유연하면서 강한 필름",
      body: "플라스토머 소재로 유연하면서 동시에 강한 2대 성능을 실현했습니다. 접고 펼치는 시공에도 잘 견디며 장기성 강도를 오래 유지합니다.",
      image: "products/po-film/premium/diastar/hero/exterior-03.webp",
    },
    {
      title: "독자 도포기술 무적성능",
      body: "독자적인 도포기술로 무적(無滴) 성능을 장기적으로 지속시켜 하우스 내 물방울 맺힘을 억제합니다.",
      image: "products/po-film/premium/diastar/hero/interior-02.webp",
    },
    {
      title: "두께 0.15mm·5년 수명",
      body: "두께 0.15mm 일본산 PO필름으로 경제수명 5년을 제공하며, 폭 10cm·길이 1m 단위 맞춤가공이 가능합니다.",
      image: "products/po-film/premium/diastar/hero/exterior-04.webp",
    },
    {
      title: "최상의 광환경",
      body: "축적된 기술과 노하우로 높은 투명도를 구현해 재배 작물과 하우스에 최상의 광환경을 제공합니다.",
      image: "products/po-film/premium/diastar/hero/interior-01.webp",
    },
  ],
  fullSpecs: [
    {
      group: "다이아스타 (ダイアスター)",
      rows: [
        ["분류", "투명필름 · 코팅 PO"],
        ["두께", "0.15 mm"],
        ["제조국가", "일본 (MKV Advance)"],
        ["경제수명", "5년"],
        ["길이 · 폭", "길이 1m, 폭 10cm 단위 맞춤가공"],
      ],
    },
  ],
  hero: {
    src: "products/po-film/premium/diastar/hero/exterior-01.webp",
    alt: "다이아스타가 시공된 비닐하우스 단지",
  },
  heroVideo: {
    src: "products/po-film/premium/diastar/farms/221101-농촌진흥청-맘모스하우스/video/exterior-01.mp4",
    poster: "products/po-film/premium/diastar/hero/exterior-01.webp",
  },
  gallery: [
    { src: "products/po-film/premium/diastar/hero/exterior-01.webp", alt: "다이아스타 시공 외관 1", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/interior-01.webp", alt: "다이아스타 하우스 내부 1", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/exterior-02.webp", alt: "다이아스타 시공 외관 2", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/interior-02.webp", alt: "다이아스타 하우스 내부 2", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/exterior-03.webp", alt: "다이아스타 시공 외관 3", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/interior-03.webp", alt: "다이아스타 하우스 내부 3", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/exterior-04.webp", alt: "다이아스타 시공 외관 4", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/interior-04.webp", alt: "다이아스타 하우스 내부 4", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/exterior-05.webp", alt: "다이아스타 시공 외관 5", year: "2022", region: "전주" },
    { src: "products/po-film/premium/diastar/hero/interior-05.webp", alt: "다이아스타 하우스 내부 5", year: "2022", region: "전주" },
  ],
  bestFarms: [
    {
      slug: "kim-sanggyu-seongju-melon",
      farmer: "김상규 마이스터",
      region: "경북 성주군",
      crop: "참외",
      round: "1회",
      note: "우리 밭의 지형에 맞는 필름을 사용하니 초물 수확도 빨라지고 출하량 증가에도 도움이 되었습니다. 2023년처럼 기온이 크게 떨어진 겨울에도 보온성이 좋아 열매 착과와 크기가 안정적으로 유지되었습니다.",
      imageTransform: { zoom: 1.5, dx: -8, dy: 12 },
      hero: {
        src: "products/po-film/premium/diastar/best-farms/kim-sanggyu-seongju-melon-v1/231006/gallery/portrait-01.webp",
        alt: "김상규 마이스터의 다이아스타 인물 사진",
      },
      gallery: [
        { src: "products/po-film/premium/diastar/best-farms/kim-sanggyu-seongju-melon-v1/231006/gallery/interior-01.webp", alt: "김상규 마이스터 하우스 내부 1" },
        { src: "products/po-film/premium/diastar/best-farms/kim-sanggyu-seongju-melon-v1/231006/gallery/interior-02.webp", alt: "김상규 마이스터 하우스 내부 2" },
        { src: "products/po-film/premium/diastar/best-farms/kim-sanggyu-seongju-melon-v1/231006/gallery/interior-03.webp", alt: "김상규 마이스터 하우스 내부 3" },
        { src: "products/po-film/premium/diastar/best-farms/kim-sanggyu-seongju-melon-v1/231006/gallery/interior-04.webp", alt: "김상규 마이스터 하우스 내부 4" },
        { src: "products/po-film/premium/diastar/best-farms/kim-sanggyu-seongju-melon-v1/231006/gallery/interior-05.webp", alt: "김상규 마이스터 하우스 내부 5" },
        { src: "products/po-film/premium/diastar/best-farms/kim-sanggyu-seongju-melon-v1/231006/gallery/interior-06.webp", alt: "김상규 마이스터 하우스 내부 6" },
      ],
    },
    {
      slug: "park-junsik-goseong-tomato",
      farmer: "박준식 농가",
      region: "경남 고성군",
      crop: "토마토",
      round: "2회",
      note: "빛, 온도, 보온을 함께 안정적으로 유지하는 환경이 필요했고, 다이아스타 필름을 사용하면서 이런 조건이 잡히기 시작하여 과실의 광택과 육질, 당도 품질이 안정되었습니다.",
      imageTransform: { dy: -4 },
      hero: {
        src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/portrait-01.webp",
        alt: "박준식 농가의 다이아스타 인물 사진",
      },
      gallery: [
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/exterior-01.webp", alt: "박준식 농가 하우스 외관 1" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/exterior-02.webp", alt: "박준식 농가 하우스 외관 2" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/exterior-03.webp", alt: "박준식 농가 하우스 외관 3" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/exterior-04.webp", alt: "박준식 농가 하우스 외관 4" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/exterior-05.webp", alt: "박준식 농가 하우스 외관 5" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/exterior-06.webp", alt: "박준식 농가 하우스 외관 6" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/exterior-07.webp", alt: "박준식 농가 하우스 외관 7" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-01.webp", alt: "박준식 농가 하우스 내부 1" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-02.webp", alt: "박준식 농가 하우스 내부 2" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-03.webp", alt: "박준식 농가 하우스 내부 3" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-04.webp", alt: "박준식 농가 하우스 내부 4" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-05.webp", alt: "박준식 농가 하우스 내부 5" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-06.webp", alt: "박준식 농가 하우스 내부 6" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-07.webp", alt: "박준식 농가 하우스 내부 7" },
        { src: "products/po-film/premium/diastar/best-farms/park-junsik-goseong-tomato-v2/250402/gallery/interior-08.webp", alt: "박준식 농가 하우스 내부 8" },
      ],
    },
    {
      slug: "shin-yunhwa-gimhae-rose",
      farmer: "신윤화 농가",
      region: "경남 김해시",
      crop: "장미",
      round: "1회",
      note: "하우스 안에서 빛이 고르게 퍼지니 나무 생육이 안정되고 꽃대와 꽃 형태도 균일하게 형성돼 생산량도 꾸준히 유지되고 있습니다.",
      imageTransform: { zoom: 1.5, dy: -10 },
      hero: {
        src: "products/po-film/premium/diastar/best-farms/shin-yunhwa-gimhae-rose-v1/240213/gallery/portrait-01.webp",
        alt: "신윤화 농가의 다이아스타 인물 사진",
      },
      gallery: [
        { src: "products/po-film/premium/diastar/best-farms/shin-yunhwa-gimhae-rose-v1/240213/gallery/exterior-01.webp", alt: "신윤화 농가 하우스 외관 1" },
        { src: "products/po-film/premium/diastar/best-farms/shin-yunhwa-gimhae-rose-v1/240213/gallery/exterior-02.webp", alt: "신윤화 농가 하우스 외관 2" },
        { src: "products/po-film/premium/diastar/best-farms/shin-yunhwa-gimhae-rose-v1/240213/gallery/interior-01.webp", alt: "신윤화 농가 하우스 내부 1" },
        { src: "products/po-film/premium/diastar/best-farms/shin-yunhwa-gimhae-rose-v1/240213/gallery/interior-02.webp", alt: "신윤화 농가 하우스 내부 2" },
        { src: "products/po-film/premium/diastar/best-farms/shin-yunhwa-gimhae-rose-v1/240213/gallery/interior-03.webp", alt: "신윤화 농가 하우스 내부 3" },
        { src: "products/po-film/premium/diastar/best-farms/shin-yunhwa-gimhae-rose-v1/240213/gallery/interior-04.webp", alt: "신윤화 농가 하우스 내부 4" },
      ],
    },
  ],
  catalogPdf: "company/catalog/diastar-2025.pdf",
  partners: ["sumitomo"],
  badges: ["Made in Japan"],
};
